[View in Colaboratory](https://colab.research.google.com/github/carvalheirafc/probabilidade_repository/blob/master/aula07/aula07.ipynb)

In [32]:
# Uploading files from your local file system

from google.colab import files
uploaded = files.upload()
for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving nyc_taxis.csv to nyc_taxis (2).csv
User uploaded file "nyc_taxis.csv" with length 5145963 bytes


In [0]:


import csv
import numpy as np

taxi_list_of_list = [[float(item) for item in row]
                    for row in list(csv.reader(open("nyc_taxis.csv", "r")))[1:]]

In [0]:
taxi = np.array(taxi_list_of_list)
print (taxi[:2])


In [0]:
taxi_ten = taxi[:10]


In [0]:
#print row 0
row_0  = taxi[0]
#print all columns in rows 391 ~ 500 
rows_391_to_500 = taxi[391:501,:]
#print a element from pos 21, 5
row_21_column_5 = taxi[21, 5]




In [0]:
trip_distance_miles = taxi[:, 7]
trip_lenght_seconds = taxi[:, 8]

#print (trip_distance_miles[:5])
#print (trip_lenght_seconds[:5])

trip_lenght_hours = trip_lenght_seconds / 3600
trip_mph = trip_distance_miles / trip_lenght_hours

#print(len(trip_mph), trip_mph[:6])

In [39]:

mph_max = trip_mph.max()
mph_mean = trip_mph.mean()

print(mph_max, mph_mean)

82800.0 32.24258580925573


In [42]:
taxi_column_means = taxi.mean(axis=1)

print(taxi_column_means)

[281.86533333 244.79266667 238.88666667 221.08133333 189.01066667]


In [0]:
#the array trip_mph is converted to a one single column array
trip_mph_2d = np.expand_dims(trip_mph, axis=1)


taxi = np.concatenate([taxi, trip_mph_2d], axis=1)
#print(taxi)

In [51]:

sorted_index_mph = np.argsort(taxi[:,15])
taxi_sorted = taxi[sorted_index_mph]
print(taxi_sorted)
#print (sorted_index_mph)

[[2.016e+03 6.000e+00 2.800e+01 ... 1.000e+00 0.000e+00 0.000e+00]
 [2.016e+03 3.000e+00 3.000e+00 ... 1.000e+00 0.000e+00 0.000e+00]
 [2.016e+03 4.000e+00 6.000e+00 ... 4.000e+00 0.000e+00 0.000e+00]
 ...
 [2.016e+03 3.000e+00 2.800e+01 ... 2.000e+00 3.204e+04 3.204e+04]
 [2.016e+03 2.000e+00 1.300e+01 ... 2.000e+00 7.056e+04 7.056e+04]
 [2.016e+03 1.000e+00 2.200e+01 ... 2.000e+00 8.280e+04 8.280e+04]]
